### ISSUE TITLE
Update for GNOME 43

### ISSUE THREAD

**Issue by siddhpant** [daniruiz/flat-remix-gtk#153]
Nautilus icons have too much padding now, whereas they show perfectly fine in [GNOME's release notes](https://release.gnome.org/43/).

On release page:

![image](https://user-images.githubusercontent.com/25429745/194705412-bd586fe8-7e9f-4866-8b3f-484eb48ebb58.png)

Using the theme:

![image](https://user-images.githubusercontent.com/25429745/194705335-8a7973c7-f718-42b2-b783-a265c7c0d70c.png)

**Comment by siddhpant** [comment]
@daniruiz Is this repo no longer maintained? There have been many theme parser errors for a long time now.

I understand you must have other commitments, but clarifying on the status of this repo will be highly appreciated. Though I see you still commit to `flat-remix-gnome`.

**Comment by daniruiz** [comment]
> @daniruiz Is this repo no longer maintained? There have been many theme parser errors for a long time now.
> 
> I understand you must have other commitments (which is perfectly fine), but clarifying on the status of this repo will be highly appreciated. Though I see you still commit to `flat-remix-gnome`.
> 
> Regardless, thanks for making this theme!

It's not unmaintained but I don't have as much time right now :( I've just checked and I hadn't updated the them for 2 years! sorry

I've pushed multiple updates today btw.

About the folder padding in nautilus, that's controlled by nautilus itself, I don't think that can be modified from the theme code

**Comment by siddhpant** [comment]
Thanks!

Though after the update, window buttons on nautilus are stretched:

![image](https://github.com/user-attachments/assets/30d0b433-e035-4d0d-8802-da19bb3d86ec)

Some theme parser errors are still there:

```
$ sudo nautilus

** (org.gnome.Nautilus:35963): WARNING **: 12:14:53.257: 
========================================================
This app cannot work correctly if run as root (not even
with sudo). Consider running `nautilus admin:/` instead.
========================================================


** Message: 12:15:00.273: Connecting to org.freedesktop.Tracker3.Miner.Files

(org.gnome.Nautilus:35963): Gtk-WARNING **: 12:15:00.346: Theme parser error: gtk.css:4963:12-17: "shade" is not a valid color name.

(org.gnome.Nautilus:35963): Gtk-WARNING **: 12:15:00.346: Theme parser error: gtk.css:5023:12-17: "shade" is not a valid color name.

(org.gnome.Nautilus:35963): Gtk-WARNING **: 12:15:00.346: Theme parser error: gtk.css:5050:12-15: "mix" is not a valid color name.

(org.gnome.Nautilus:35963): Gtk-WARNING **: 12:15:00.346: Theme parser error: gtk.css:5054:12-15: "mix" is not a valid color name.

(org.gnome.Nautilus:35963): Gtk-WARNING **: 12:15:00.347: Theme parser warning: gtk.css:5255:3-5256:1: Expected ';' at end of block

(org.gnome.Nautilus:35963): Gtk-WARNING **: 12:15:00.347: Theme parser error: gtk.css:5286:3-19: No property named "-gtk-icon-effect"

** (org.gnome.Nautilus:35963): WARNING **: 12:15:00.644: Unable to get contents of the bookmarks file: Error opening file /root/.gtk-bookmarks: No such file or directory
```

Regarding folder padding, ~~idk if it was the case before as I stopped getting bothered about it, but~~ the padding seems to be fixed now (Edit: tried on another machine, update fixes it!):

![image](https://github.com/user-attachments/assets/297f0584-24b5-46a4-9ea7-77630336f66b)

![image](https://github.com/user-attachments/assets/fa28c709-3afe-4580-9195-60f4d446e665)

![image](https://github.com/user-attachments/assets/cf99e6db-26b0-481a-ac88-50ea7083b1f7)
